problem: C

A:
	python A.day.py < A.in > A.out
	cat A.out

Al:
	python A.day.py < Al.in > Al.out
	cat Al.out

B:
	gcc B.c -o B.exe -O2 -lm -Wall
	./B.exe < B-small-attempt0.in > B.out
	cat B.out

Bl:
	python B.py < B-large.in > B.out

C:
	python C.py < C.txt > C.out
	cat C.out
