---
available:
  py: python
  rb: ruby
  java: java
  txt: text
  c: c
  cpp: c++
  go: go
  lua: lua
about:
  python:
    kind: interpreted
    run: python {0}
  ruby:
    kind: interpreted
    run: jruby {0}
  text:
    kind: interpreted
    run: cat {0}
  go:
    kind: interpreted
    run: go run {0}
  lua:
    kind: interpreted
    run: lua {0}
  c:
    kind: compiled
    build: gcc {0} -o {0}.exe
    run: "./{0}.exe"
    clean: rm {0}.exe
  java:
    kind: vm
    build: javac {0}
    run: java {0}
